name: bildverpixelung
channels:
  - conda-forge
  - defaults
dependencies:
  - pyinstaller=6.18.0
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - click=8.3.1
  - dlib=19.24.2
  - expat=2.7.3
  - face_recognition=1.3.0
  - face_recognition_models=0.3.0
  - icu=78.2
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libopenblas=0.3.30
  - libpng=1.6.54
  - libsqlite=3.51.2
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - ncurses=6.5
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.6.1
  - packaging=25.0
  - pillow=11.3.0
  - pip=25.3
  - pthread-stubs=0.4
  - python=3.10.15
  - python_abi=3.10
  - readline=8.3
  - setuptools=80.10.1
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - blinker==1.9.0
      - flask==3.1.2
      - flask-cors==6.0.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - werkzeug==3.1.5
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/bildverpixelung
