name: bildverpixelung
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pillow=11.3.0
  - click=8.3.1
  - flask=3.1.2
  - flask-cors=6.0.2
  - dlib=19.24.2
  - face_recognition=1.3.0
  - pyinstaller=6.18.0
  - pkg_resources
  - pip
  - pip:
      - blinker==1.9.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - werkzeug==3.1.5
      - pywebview==6.1
