name: Build-EXE
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout-repo-content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: 3.10.15 #install the python needed
          auto-update-conda: true
          activate-environment: bildverpixelung
          environment-file: backend/environment-windows.yml
          use-mamba: true
      - name: Verify conda
        shell: bash -l {0}
        run: |
          conda info
          python --version
      - run: conda run -n bildverpixelung python -m PyInstaller --onefile backend/api/app.py
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-build
          path: D:\a\Bild-Verpixelung\Bild-Verpixelung\dist
          retention-days: 2
  build-mac:
    runs-on: macos-latest
    steps:
      - name: checkout-repo-content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: 3.10.15 #install the python needed
          auto-update-conda: true
          activate-environment: bildverpixelung
          environment-file: backend/environment-mac.yml
          use-mamba: true
      - name: Verify conda
        shell: bash -l {0}
        run: |
          conda info
          python --version
      - run: conda run -n bildverpixelung python -m PyInstaller --onefile backend/api/app.py

      - uses: actions/upload-artifact@v4
        with:
          name: Mac-build
          path: /Users/runner/work/Bild-Verpixelung/Bild-Verpixelung/dist
          retention-days: 1
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo-content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: 3.10.15 #install the python needed
          auto-update-conda: true
          activate-environment: bildverpixelung
          environment-file: backend/environment-mac.yml
          use-mamba: true
      - name: Verify conda
        shell: bash -l {0}
        run: |
          conda info
          python --version
      - run: conda run -n bildverpixelung python -m PyInstaller --onefile backend/api/app.py

      - uses: actions/upload-artifact@v4
        with:
          name: Linux-build
          path: /home/runner/work/Bild-Verpixelung/Bild-Verpixelung/dist
          retention-days: 1
