name: Build-EXE
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout-repo-content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: 3.10.15 #install the python needed
          auto-update-conda: true
          active-environmennt: bildverpixelung
          environment-file: backend/environment-win.yml
          use-mamba: true
      - name: Verify conda
        shell: bash -l {0}
        run: |
          conda info
          python --version
      - run: conda run -n test python -m PyInstaller --onefile backend/app.py

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: /home/runner/work/Bild-Verpixelung/Bild-Verpixelung/dist/
